spring.application.name=registerParticipes


# conexion con la base de datos

spring.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=RegistroDeParticipantes;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=Admin12345
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver


spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform= org.hibernate.dialect.SQLServerDialect


